apiVersion: apps/v1
kind: Deployment
metadata:
  name: listr-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: app-instance
      app.kubernetes.io/name: app
  template:
    metadata:
      labels: # THIS LABELS MUST MATCH WITH SPEC -> SELECTOR LABELS
        app.kubernetes.io/instance: app-instance
        app.kubernetes.io/name: app
    spec:
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      containers:
      - name: listr-db
        image: quay.io/upslopeio/express-sample-app:d90c742ee626048c4d1e2032eb836255e4036561
        ports:
        - name: http
          protocol: TCP
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pv-claim
          subPath: data
        env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        resources: {}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            port: 5432
            path: /
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            port: http
            path: /
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600