apiVersion: v1
kind: Service
metadata:
  name: listr-db
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: app-instance
    app.kubernetes.io/name: app
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432
  sessionAffinity: None