apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcs-trigger-db
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcs-trigger-db
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcs-trigger-db
subjects:
  - kind: ServiceAccount
    name: vcs-trigger-db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vcs-trigger-db
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger-db
spec:
  params:
      - name: source-repo
        description: Source code repository
      - name: sha
        description: Precise SHA of the commit to build
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: listr-db-app-pipeline-
      spec:
        pipelineRef:
          name: mohamed-keerthana-listr-db-app-deploy
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: listr-db
          - name: source-repo
            value: https://github.com/cloud-native-garage-method-cohort/listr-db
          - name: sha # introduce new param
            value: $(tt.params.sha) # use value from trigger event
          - name: source-image
            value: quay.io/derinsolao/listr-db
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: production-repository
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: vcs-trigger-db
spec:
  params:
    - name: source-repo
      value: $(body.repository.url)
    - name: sha
      value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vcs-trigger-db
spec:
  serviceAccountName: vcs-trigger-db
  triggers:
    - bindings:
        - ref: vcs-trigger-db
      template:
        name: vcs-trigger-db
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vcs-trigger-db
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-vcs-trigger-db
    weight: 100


